/*--------------------------------------------------------------------------
XC2365A.H

Register Declarations for XC2365A Processor
Copyright (c) 2005-2008 Keil An ARM Company
All rights reserved.
--------------------------------------------------------------------------*/
#ifndef __XC2365A_H__
#define __XC2365A_H__

#ifdef WIN32
	#include "XC2xxx_M_A_X_PC.h"
#else
	#include "XC2xxx_M_A_X.h"
#endif

#endif